### PR TITLE
Open developer terminal

### PR DESCRIPTION
**Pull request by anjannath**

### CODE REVIEW

**Comment by gbraad** [comment]
> body: "Only supported on windows currently"

Why is this still WIP ?

**Comment by anjannath** [comment]
@gbraad I wanted to remove WIP once the macOS part is also implemented

**Comment by gbraad** [comment]
No worries. I think this is a good start.

**Comment by anjannath** [comment]
> No worries. I think this is a good start.

alright, removed the WIP and added few small fixes as well

**Comment by gbraad** [comment]
Will take a look

**Review by gbraad — APPROVED** [review]

**Pull request merged**
