### PR TITLE
[Test] Linux release

### LINKED ISSUE #144: [Spike] Investigate what is needed to make the tray work properly on Linux

### PR DESCRIPTION
**Pull request by gbraad**

### CODE REVIEW

**Comment by gbraad** [comment]
Issues:

  * does not show `Tray` on Gnome/Fedora
  *

**Comment by cfergeau** [comment]
> does not show Tray on Gnome/Fedora

Maybe https://extensions.gnome.org/extension/2890/tray-icons-reloaded/ or https://extensions.gnome.org/extension/1674/topiconsfix/ would help?

**Comment by gbraad** [comment]
I'll reach out to Robert after I tested with this.

**Comment by gbraad** [comment]
@evidolob what are your thoughts? It seems supporting Linux is not high priority, but what are your thoughts to get this shown on the tray? It seems it is a hit and miss for Linux users.

**Comment by evidolob** [comment]
I can test tray app on linux, Fedora with gnome, and provide feedback

**Comment by praveenkumar** [comment]
closing it because we are not going to actively maintain it.

**Pull request closed without merging**
