### PR TITLE
Change tray clicks and move menu functions around

### PR DESCRIPTION
**Pull request by gbraad**

### CODE REVIEW

**Comment by anjannath** [comment]
@gbraad the menu items are not aligned properly, i think `Open logs` should also align with the items below it?
image

**Comment by gbraad** [comment]
I think I already pushed a change for this... hold on, more coming

**Comment by anjannath** [comment]
@gbraad Needs rebase and also make the following change(add `enablePreferredSizeMode: true` to `webPreference` of ministatus window), this should help with the button alignment issue @praveenkumar was seeing.. 
```patch
diff --git a/src/main.ts b/src/main.ts
index 323f860..d12e707 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -258,7 +258,8 @@ const appStart = async function() {
     frame: false,
     titleBarStyle: 'hidden',
     webPreferences: {
-      preload: path.join(__dirname, "preload-main.js")
+      preload: path.join(__dirname, "preload-main.js"),
+      enablePreferredSizeMode: true
     }
   })
   miniStatusWindow.setMenuBarVisibility(false)
```

**Comment by gbraad** [comment]
@anjannath fixed

**Review by anjannath — APPROVED** [review]

**Pull request merged**
