### PR TITLE
Fixes #63 adds PresetSelection to Wizard and Configuration

### LINKED ISSUE #63: Add preset option to configuration
* Should this be a `ToggleGroup` ?
  * How about displaying the preset specific information
    * description
    * CPU, memory and disk size changes

### PR DESCRIPTION
**Pull request by gbraad**
Added `PresetSelection` to the `configurationWindow` and the SetupWizard.

### CODE REVIEW

**Comment by gbraad** [comment]
The state in the `configurationWindow` does not reflect the value from the config we receive. This is most likely an issue with the component itself. haven't been able to pinpoint this yet. It does however work correctly for the `Wizard`.

**Comment by anjannath** [comment]
Currently when the config window first loads, the currently configured Preset is not selected in the config UI

```
PS C:\Users\anath\redhat\tray-electron> crc config view
- network-mode                          : user
- preset                                : podman
```

image

**Comment by gbraad** [comment]
@anjannath I mentioned this in comment https://github.com/code-ready/tray-electron/pull/111#issuecomment-1019901994

This is resolved in https://github.com/code-ready/crc-react-components/commit/38bafa7f195f802b39d90832267c40c0aa4902e3

**Comment by gbraad** [comment]
Should work now

**Review by anjannath — APPROVED** [review]

**Pull request merged**
