### PR TITLE
Resolve #130 Add dialog API

### LINKED ISSUE #130: Spike adding a modal dialog option
For several actions, like exiting the wizard, deleting the instance, or adding the pull-secret during start, we need to show a modal dialog. The issue is that only a 'native' dialog is available to perform such an action.

### PR DESCRIPTION
**Pull request by evidolob**
This Dialog API is pretty straightforward:

On main thread import `showDialog` function from `src/dialog.ts`,
example of usage:
```typescript
const result = await showDialog(parentWindowOrUndefined, {title: "Foo", message: "Bar?'}, "Yes", "No");
```

On any renderer thread, which loaded with `preload-main.js`, `showModalDialog` function exposed in `window.api` object.
Example:

```typescript
const result = await document.api.showModalDialog('Title', 'Message', 'Yes', 'No', 'Cancel');
```

A small demo:

https://user-images.githubusercontent.com/929743/153597806-ae4e2d72-a3b0-4c61-87de-77ec4bff7fbd.mov

### CODE REVIEW

**Comment by gbraad** [comment]
can you rebase this @evidolob ?

**Review by gbraad — APPROVED** [review]

**Comment by gbraad** [comment]
Can you provide an `example` for the `onDeleteClicked` ? I'll create a new issue to track.

**Comment by evidolob** [comment]
Sure

**Comment by gbraad** [comment]
I created #142

**Pull request merged**
